name: enetclean2
channels:
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - bleach==1.5.0
  - cycler==0.10.0
  - h5py==2.7.1
  - html5lib==0.9999999
  - keras==2.0.8
  - markdown==2.6.9
  - matplotlib==2.1.0
  - numpy==1.13.3
  - olefile==0.44
  - pillow==4.3.0
  - protobuf==3.4.0
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - pytz==2017.2
  - pyyaml==3.12
  - scipy==0.19.1
  - six==1.11.0
  - tensorflow-gpu==1.3.0
  - tensorflow-tensorboard==0.1.8
  - werkzeug==0.12.2
prefix: /home/pmelissi/miniconda2/envs/enetclean2

